language: python
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8
python:
  - 2.7
before_install:
  - "git clone git://github.com/n1k0/casperjs.git"
  - "sudo ln -s `pwd`/casperjs/bin/casperjs /usr/local/bin"
install: pip install Django==$DJANGO_VERSION --use-mirrors
script: make test
